### ISSUE TITLE
Vega lite integration

### ISSUE THREAD

**Issue by domoritz** [vega/ipython-vega#10]
Call this way:

```python
from vega import vegalite
vegalite.display(spec)
```

Then display the visualization.

**Comment by amitkaps** [comment]
Have implemented this exactly same as the polestar and voyager, using the tools.py. Obviously, supports the current vegalite spec. Have sent you a pull request. Please review. 

Working ipython example below. 
http://nbviewer.ipython.org/github/amitkaps/ipython-vega/blob/master/Example.ipynb

**Comment by domoritz** [comment]
Issue with similar intention https://github.com/vega/ipython-vega/issues/6

**Comment by domoritz** [comment]
Let's pick it up again now that 1.0 is out. Also see discussion in https://github.com/ellisonbg/altair/issues/62

**Comment by amitkaps** [comment]
Yes we should. I will start looking at Vega-lite 1.0 and the suggested discussion and build on the earlier example.

**Comment by domoritz** [comment]
Use nbextension https://blog.jupyter.org/2016/04/15/notebook-4-2/
