### ISSUE TITLE
Update polestar and voyager

### ISSUE THREAD

**Issue by domoritz** [vega/ipython-vega#17]
Will do very soon. There are some pending changes in compass and voyager.

**Comment by yuvipanda** [comment]
Any updates? :)

**Comment by domoritz** [comment]
@kanitw and I are working hard on getting a few small issues resolved. I will push a new release some time this week.

**Comment by domoritz** [comment]
There are still some odd issues in compass (https://github.com/vega/compass/issues/142) but I've pushed an update with the latest polestar and voyager. We should do #20 to make the update process easier.
