### ISSUE TITLE
Vega integration

### ISSUE THREAD

**Issue by domoritz** [vega/ipython-vega#18]
Potentially using vega embed

**Comment by SamPenrose** [comment]
Hello, I'm interested in this work. Do you have a TODO list for it? I ran pyflakes on the PR and put the output into comments; next I'm going to drop my own data into a notebook and see what happens. I can start filing issues and/or hacking but if you have a plan you can share I'd be happy to look for opportunities to follow your lead.

**Comment by domoritz** [comment]
Hi @SamPenrose. Thanks for your comments. I'll look at them early next week.

I have some TODOs in the readme. Mainly I would like to get Polestar and Voyager working again and also add support for some kind of export from voyager and polestar. And also save state. Check out the issues I created. 

I'm still not quite sure what the right architecture is but I think it would be great if we could somehow serve the data from a server extension rather than embedding the data as json in generated HTML. 

If anything sounds interesting to you, feel free to look into them.
