### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by jluttine** [vega/ipython-vega#22]
I might be doing something wrong here, but I couldn't import vega using Python 3.5.

```console
ImportError                               Traceback (most recent call last)
<ipython-input-1-4f3fd77079e7> in <module>()
----> 1 import vega

/.../lib/python3.5/site-packages/vega/__init__.py in <module>()
----> 1 import tool
      2 import polestar
      3 import voyager
      4 import vegalite

ImportError: No module named 'tool'
```

Does it currently support only Python 2? Relative imports don't work like that in Python 3, if I remember correctly, you'd need to use `import .tool`. I can try to work on a Python 3 patch if needed. Any thoughts?

**Comment by domoritz** [comment]
I didn't test with Python 3.

**Comment by jakevdp** [comment]
Py3K support is in this PR: https://github.com/vega/ipython-vega/pull/24
